import "./globals.css";
import { Inter } from "next/font/google";
import Navigation from "../src/components/navigation/navigation";
import Cursor from "../src/components/cursor/Cursor";
import Footer from "../src/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Cursor />
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
